# Generated by Django 5.2 on 2025-04-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_pembelian_produk_detailpembelian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_nota', models.CharField(max_length=100, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pembayaran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kembalian', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_jual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.produk')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_penjualan', to='userapp.penjualan')),
            ],
        ),
    ]
