# Generated by Django 5.2 on 2025-04-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_penjualan_detailpenjualan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KartuStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=10)),
                ('jumlah', models.IntegerField()),
                ('sumber', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.produk')),
            ],
        ),
    ]
