# Generated by Django 5.2 on 2025-04-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_kartustok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
