# Generated by Django 5.2 on 2025-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_penjualan_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='nomor_btb',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
