# Generated by Django 5.2 on 2025-07-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_pembelian_nomor_btb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='DetailReturPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=15)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.produk')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_retur_pembelian', to='userapp.returpembelian')),
            ],
        ),
        migrations.CreateModel(
            name='ReturPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.penjualan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailReturPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.produk')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_retur_penjualan', to='userapp.returpenjualan')),
            ],
        ),
    ]
