# Generated by Django 5.2 on 2025-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_returpembelian_detailreturpembelian_returpenjualan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returpenjualan',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='detailreturpenjualan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
