# Generated by Django 5.2 on 2025-08-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_returpenjualan_keterangan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returpembelian',
            name='keterangan',
        ),
    ]
