# Generated by Django 5.2 on 2025-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_returpembelian_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailreturpembelian',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
